## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
## Author:  UK (Initials)
##
## This software is for demonstration purposes only and is not supported
## by VyOS or the dev.
##
# run the playbook with the -v option to see the collected facts:
#    ansible-playbook -i vyos-routers DMVPN-Spoke.yml -vvv
#
# NOTE: connection network_cli has been introduced in Ansible 2.5
---
  - hosts: vyos
    connection: network_cli
    gather_facts: 'no'

    vars_prompt:
    - name: "wanip1"
      prompt: "Enter the Public IP of the router."
      private: no
    - name: "tunip1"
      prompt: "Enter a tunnel IP. Example 172.16.16.1/27."
      private: no
    - name: "secret1"
      prompt: "Enter a passphrase for the tunnel (8 Character long due to Cisco™ routers)."
      private: yes
    - name: "secret2"
      prompt: "Enter the same passphrase you did for then tunnel (8 Character long due to Cisco™ routers)."

      