## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
## Author:  UK (Initials)
##
## This software is for demonstration purposes only and is not supported
## by VyOS or the dev.
##
# run the playbook with the -v option to see the collected facts:
#    ansible-playbook -i vyos-routers DMVPN-Spoke.yml -vvv
#
# NOTE: connection network_cli has been introduced in Ansible 2.5
---
  - hosts: vyos
    connection: network_cli
    gather_facts: 'no'

    vars_prompt:
    - name: "wanip1"
      prompt: "Enter the Public IP of the router."
      private: no
    - name: "tunip1"
      prompt: "Enter a tunnel IP. Example 172.16.16.1/27."
      private: no
    - name: "secret1"
      prompt: "Enter a passphrase for the tunnel (8 Character long due to Cisco™ routers)."
      private: yes
    - name: "secret2"
      prompt: "Enter the same passphrase you did for then tunnel (8 Character long due to Cisco™ routers)."

    tasks:
      - name: Phase 2.2 DMVPN Spoke Configuration.
        vyos_config:
          lines:

          set interfaces tunnel tun100 address 172.16.253.133/29
set interfaces tunnel tun100 local-ip 0.0.0.0
set interfaces tunnel tun100 encapsulation gre
set interfaces tunnel tun100 multicast enable
set interfaces tunnel tun100 parameters ip key 1

set protocols nhrp tunnel tun100 cisco-authentication 68E80Uvj
set protocols nhrp tunnel tun100 holding-time 600
set protocols nhrp tunnel tun100 map 172.16.253.134/29 nbma-address 194.28.99.47
set protocols nhrp tunnel tun100 map 172.16.253.134/29 register
set protocols nhrp tunnel tun100 multicast nhs
set protocols nhrp tunnel tun100 redirect
set protocols nhrp tunnel tun100 shortcut

set vpn ipsec esp-group ESP-HUB compression disable
set vpn ipsec esp-group ESP-HUB lifetime 28800
set vpn ipsec esp-group ESP-HUB mode transport
set vpn ipsec esp-group ESP-HUB pfs dh-group21
set vpn ipsec esp-group ESP-HUB proposal 1 encryption aes256
set vpn ipsec esp-group ESP-HUB proposal 1 hash sha256
set vpn ipsec esp-group ESP-HUB proposal 2 encryption aes256
set vpn ipsec esp-group ESP-HUB proposal 2 hash sha256
set vpn ipsec ike-group IKE-HUB close-action none
set vpn ipsec ike-group IKE-HUB ikev2-reauth no
set vpn ipsec ike-group IKE-HUB key-exchange ikev1
set vpn ipsec ike-group IKE-HUB lifetime 86400
set vpn ipsec ike-group IKE-HUB proposal 1 dh-group 21
set vpn ipsec ike-group IKE-HUB proposal 1 encryption aes256
set vpn ipsec ike-group IKE-HUB proposal 1 hash sha256
set vpn ipsec ike-group IKE-HUB proposal 2 dh-group 21
set vpn ipsec ike-group IKE-HUB proposal 2 encryption aes256
set vpn ipsec ike-group IKE-HUB proposal 2 hash sha256

set vpn ipsec ipsec-interfaces interface eth0

set vpn ipsec profile NHRPVPN authentication mode pre-shared-secret
set vpn ipsec profile NHRPVPN authentication pre-shared-secret {{ secret2 }}
set vpn ipsec profile NHRPVPN bind tunnel tun100
set vpn ipsec profile NHRPVPN esp-group ESP-HUB
set vpn ipsec profile NHRPVPN ike-group IKE-HUB